export const CURRENT_USER = {
  name: "Arjun Singh",
  initials: "AS",
  title: "Full Stack Developer",
  company: "Freelance",
  connections: 142,
  profileViews: 48,
};

export const STORIES = [
  { id: 1, name: "Priya S.",    initials: "PS", seen: false, color: "bg-violet-500" },
  { id: 2, name: "Rahul M.",    initials: "RM", seen: false, color: "bg-blue-500"   },
  { id: 3, name: "Neha K.",     initials: "NK", seen: true,  color: "bg-emerald-500"},
  { id: 4, name: "Vikram J.",   initials: "VJ", seen: true,  color: "bg-amber-500"  },
  { id: 5, name: "Ananya R.",   initials: "AR", seen: false, color: "bg-rose-500"   },
];

export const INITIAL_POSTS = [
  {
    id: 1,
    author: "Priya Sharma",
    initials: "PS",
    avatarColor: "bg-violet-100 text-violet-700",
    title: "Product Manager @ Google",
    time: "2h ago",
    visibility: "public",
    content: "Just wrapped up our Q2 design sprint — biggest takeaway: constraint breeds creativity.\n\nWhen you give a team 3 days instead of 3 weeks, the ideas that survive are the ones that truly matter. We shipped a feature we'd debated for 6 months — in 72 hours. 🚀\n\nWhat's your best constraint-driven win?",
    tags: ["DesignThinking", "ProductManagement"],
    likes: 148,
    comments: 23,
    shares: 12,
    liked: false,
    saved: false,
    reposted: false,
    commentList: [
      { author: "Rahul M.", initials: "RM", text: "This is so true. Parkinson's law at its finest!", time: "1h ago" },
      { author: "Ananya R.", initials: "AR", text: "We did something similar — best sprint of the year 🔥", time: "45m ago" },
    ],
  },
  {
    id: 2,
    author: "Rahul Mehta",
    initials: "RM",
    avatarColor: "bg-blue-100 text-blue-700",
    title: "Frontend Engineer @ Swiggy",
    time: "5h ago",
    visibility: "connections",
    content: "Hot take: the best engineers I've worked with are those who can explain complex systems in simple terms.\n\nTechnical depth matters, but communication is the force multiplier that 10x's a team.\n\nWho do you think is more valuable — a brilliant engineer who can't explain their work, or a good engineer who can?",
    tags: ["EngineeringCulture", "SoftSkills"],
    likes: 312,
    comments: 67,
    shares: 44,
    liked: false,
    saved: false,
    reposted: false,
    commentList: [
      { author: "Vikram J.", initials: "VJ", text: "Communication + technical depth is the dream combo. One without the other creates bottlenecks.", time: "4h ago" },
    ],
  },
  {
    id: 3,
    author: "Neha Kapoor",
    initials: "NK",
    avatarColor: "bg-emerald-100 text-emerald-700",
    title: "Data Scientist @ Flipkart",
    time: "1d ago",
    visibility: "public",
    content: "We reduced recommendation latency by 60% using a two-stage retrieval model — candidate generation → re-ranking with a lightweight neural ranker.\n\nKey insight: you don't need a single perfect model. Stage them.\n\nSharing the full architecture breakdown in a blog post next week. Drop a 🔔 if you want a ping when it goes live!",
    tags: ["MachineLearning", "RecSys", "MLOps"],
    likes: 529,
    comments: 91,
    shares: 78,
    liked: false,
    saved: false,
    reposted: false,
    commentList: [
      { author: "Priya S.", initials: "PS", text: "Brilliant! Would love to see the architecture diagram 🙌", time: "22h ago" },
      { author: "Arjun S.", initials: "AS", text: "Subscribed. This is exactly what our team needs.", time: "20h ago" },
    ],
  },
  {
    id: 4,
    author: "Vikram Joshi",
    initials: "VJ",
    avatarColor: "bg-amber-100 text-amber-700",
    title: "DevOps Lead @ Infosys",
    time: "2d ago",
    visibility: "public",
    content: "Interviewer: 'Where do you see yourself in 5 years?'\n\nMe in 2019: 'Senior developer'\nMe in 2024: 'Still googling how to center a div'\n\n...on a serious note though, the best engineers I know are the ones who never stopped being comfortable saying 'I don't know — let me find out.' 🎯",
    tags: ["CareerAdvice", "TechHumor"],
    likes: 1204,
    comments: 143,
    shares: 207,
    liked: false,
    saved: false,
    reposted: false,
    commentList: [
      { author: "Rahul M.", initials: "RM", text: "LOL the CSS joke will never die 😂", time: "2d ago" },
    ],
  },
];

export const SUGGESTED_USERS = [
  { name: "Ananya Rao",     initials: "AR", title: "UX Designer @ Zomato",     mutual: 9  },
  { name: "Karan Malhotra", initials: "KM", title: "Backend Eng @ PhonePe",    mutual: 14 },
  { name: "Divya Nair",     initials: "DN", title: "PM @ Microsoft India",      mutual: 6  },
];
